# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d5530f84785c643a54f3e4afc6ef9c4f9e306dc87fa3f18c1b5f5eea8331bae49b66dd6440e3a86786ae132f2a4843a37f27f3dbe8db7b202b2145d9e5ad79a

test:
  secret_key_base: 68414670edf9fae296cc5a4202d6105089bd64a318fbe51b6d00a6c58a1f5f9b9a12f26a9d281db4ee0b0419ae3271f585b369ed6490f3a3f5c85bc6989d8502

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
